//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: service.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Greeter_GreeterClient`, then call methods of this protocol to make API calls.
public protocol Greeter_GreeterClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Greeter_GreeterClientInterceptorFactoryProtocol? { get }

  func greet(
    _ request: Greeter_Person,
    callOptions: CallOptions?
  ) -> UnaryCall<Greeter_Person, Greeter_Greeting>
}

extension Greeter_GreeterClientProtocol {
  public var serviceName: String {
    return "greeter.Greeter"
  }

  /// Unary call to Greet
  ///
  /// - Parameters:
  ///   - request: Request to send to Greet.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func greet(
    _ request: Greeter_Person,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Greeter_Person, Greeter_Greeting> {
    return self.makeUnaryCall(
      path: "/greeter.Greeter/Greet",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGreetInterceptors() ?? []
    )
  }
}

public protocol Greeter_GreeterClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'greet'.
  func makeGreetInterceptors() -> [ClientInterceptor<Greeter_Person, Greeter_Greeting>]
}

public final class Greeter_GreeterClient: Greeter_GreeterClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Greeter_GreeterClientInterceptorFactoryProtocol?

  /// Creates a client for the greeter.Greeter service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Greeter_GreeterClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Greeter_GreeterProvider: CallHandlerProvider {
  var interceptors: Greeter_GreeterServerInterceptorFactoryProtocol? { get }

  func greet(request: Greeter_Person, context: StatusOnlyCallContext) -> EventLoopFuture<Greeter_Greeting>
}

extension Greeter_GreeterProvider {
  public var serviceName: Substring { return "greeter.Greeter" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Greet":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Greeter_Person>(),
        responseSerializer: ProtobufSerializer<Greeter_Greeting>(),
        interceptors: self.interceptors?.makeGreetInterceptors() ?? [],
        userFunction: self.greet(request:context:)
      )

    default:
      return nil
    }
  }
}

public protocol Greeter_GreeterServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'greet'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGreetInterceptors() -> [ServerInterceptor<Greeter_Person, Greeter_Greeting>]
}
